### ISSUE TITLE
Duplice Newtonsoft.Json.dll issue

### ISSUE THREAD

**Issue by oprel** [SomethingWeMade/Sound-Shout#13]
Since the 2020 version Unity has started to bundle Newtonsoft.Json.dll as an internal tool (I think they even optimized it a bit to work better with il2cpp). Sadly this gives a duplicate assembly error with the exact same dll that you include! I'm not sure how to fix this without breaking functionality for versions on 2019 and earlier.

Just a small issue that's keeping me from being up-to-date with the git repo through the package manager! Since the only real workaround is manually copying over the package and deleting the dll.

**Comment by NikMikk** [comment]
This has now been fixed by recompiling the Google APIs with their latest version
https://github.com/googleapis/google-api-dotnet-client/releases/tag/v1.57.0
