### ISSUE TITLE
Can't access settings when loaded from immutable source.

### ISSUE THREAD

**Issue by oprel** [SomethingWeMade/Sound-Shout#2]
If you load this package into your project via the git link or a local tarball the entire package is placed in an [immutable folder ](https://docs.unity3d.com/Manual/upm-concepts.html). This means you can't change the settings in the Settings scriptable object and you get errors for missing .meta files which can't be added.

**Comment by NikMikk** [comment]
This is new, thanks Unity.

There are two solutions:

- Make Sound Shout work inside the Assets folder under its own folder. 

- Storing Settings ScriptableObject asset is stored under Assets. It would probably fix things but it makes little sense that it lies there by itself.

What do you think?

**Comment by oprel** [comment]
Yes, good question! One one hand it might be nice to house Sound Shout inside the assets folder and making place for things like expanding the way the Scriptable Object works and what kind of fields it's mirroring to the spreadsheet. But on the other hand it's probably neater to have everything reside in Packages. Really up to you! 

I'm kind of leaning towards making a settings object inside the Assets/Audio folder when you are done with setup. Since we can kind of assume that Sound Shout has complete control over that folder.

**Comment by NikMikk** [comment]
This is fixed in #11 

I store the settings assets inside "Assets/Audio/" but it can be moved to wherever now. Another change is that the Settings file now contains the json_secret.json data inside of it so you'll have to add that using the "Locate client_secret.json" button or manually inside the Sound Shout Setting asset.
