### ISSUE TITLE
'clients_secret.json' is saved as a YAML file rather than a JSON file

### ISSUE THREAD

**Issue by oprel** [SomethingWeMade/Sound-Shout#3]
'clients_secret.json' is saved as a YAML file when it is copied over to the EditorWindow folder. This makes it impossible for the JSON parser to parse the file.

**Comment by NikMikk** [comment]
#4 should have fixed this. Remove your old client_secret file and use the "Locate client secret" button inside the Sound Shout window

**Comment by oprel** [comment]
Thank you, that fixes it!
