### ISSUE TITLE
When I Update Spreadsheet all References marked Delete are changed to TODO.

### ISSUE THREAD

**Issue by oprel** [SomethingWeMade/Sound-Shout#8]
This is probably because they are skipped when creating audio references.

Also would like a way to just purge all the entries marked as Delete on both ends! Maybe an extra button?

**Comment by NikMikk** [comment]
I'd love to purge it on both ends but I chose to not implement it as they still exist inside FMOD. If the FMOD event is assigned to a bank it will be included even though it might never be used.

Have not figured out any way to delete them programmatically inside FMOd yet, not sure if deleting the .meta file from the FMOD project is enough to count them as deleted.

**Comment by oprel** [comment]
True, but it's not like it makes events in FMOD when you add them in SoundShout. It would actually be more confusing if it also tries to delete an FMOD event when it is purging entries marked as Delete.

Also almost all of the events we marked as Delete were just To-Do before that, we changed our mind before implementing them. There's almost never an FMOD event to delete.

It's just pretty difficult to successfully remove events at the moment, since you need to remove them from both the sheet and your unity project at the same time, without anyone updating in the meantime. And since we work on multiple branches, you need to do this for every branch you have.

**Comment by NikMikk** [comment]
This has been fixed in #14 by removing all entries marked as **Delete** altogether.
